name 'augustus'
maintainer 'Eagle Genomics Ltd'
maintainer_email 'chef@eaglegenomics.com'
license 'apachev2'
description 'Installs/Configures augustus'
long_description 'Installs/Configures augustus'
source_url 'https://github.com/EagleGenomics-cookbooks/augustus'
issues_url 'https://github.com/EagleGenomics-cookbooks/augustus/issues'
version '1.0.0'

depends 'build-essential'
depends 'apt'
